#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Learning")]
	public partial class VallabaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttab_VA_PAYANAM(tab_VA_PAYANAM instance);
    partial void Updatetab_VA_PAYANAM(tab_VA_PAYANAM instance);
    partial void Deletetab_VA_PAYANAM(tab_VA_PAYANAM instance);
    partial void Inserttab_VA_SWAMY_REGISTRATION(tab_VA_SWAMY_REGISTRATION instance);
    partial void Updatetab_VA_SWAMY_REGISTRATION(tab_VA_SWAMY_REGISTRATION instance);
    partial void Deletetab_VA_SWAMY_REGISTRATION(tab_VA_SWAMY_REGISTRATION instance);
    partial void Inserttab_VA_BUS_BOOKING(tab_VA_BUS_BOOKING instance);
    partial void Updatetab_VA_BUS_BOOKING(tab_VA_BUS_BOOKING instance);
    partial void Deletetab_VA_BUS_BOOKING(tab_VA_BUS_BOOKING instance);
    partial void Inserttab_VA_PAYANAM_BUS_DETAIL(tab_VA_PAYANAM_BUS_DETAIL instance);
    partial void Updatetab_VA_PAYANAM_BUS_DETAIL(tab_VA_PAYANAM_BUS_DETAIL instance);
    partial void Deletetab_VA_PAYANAM_BUS_DETAIL(tab_VA_PAYANAM_BUS_DETAIL instance);
    #endregion
		
		public VallabaiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LearningConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VallabaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VallabaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VallabaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VallabaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tab_VA_PAYANAM> tab_VA_PAYANAMs
		{
			get
			{
				return this.GetTable<tab_VA_PAYANAM>();
			}
		}
		
		public System.Data.Linq.Table<tab_VA_SWAMY_REGISTRATION> tab_VA_SWAMY_REGISTRATIONs
		{
			get
			{
				return this.GetTable<tab_VA_SWAMY_REGISTRATION>();
			}
		}
		
		public System.Data.Linq.Table<tab_VA_BUS_BOOKING> tab_VA_BUS_BOOKINGs
		{
			get
			{
				return this.GetTable<tab_VA_BUS_BOOKING>();
			}
		}
		
		public System.Data.Linq.Table<tab_VA_PAYANAM_BUS_DETAIL> tab_VA_PAYANAM_BUS_DETAILs
		{
			get
			{
				return this.GetTable<tab_VA_PAYANAM_BUS_DETAIL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_VA_PAYANAM")]
	public partial class tab_VA_PAYANAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _payanam_ID;
		
		private int _year;
		
		private string _payanam_TITLE;
		
		private System.DateTime _payanam_STARTDATE;
		
		private System.DateTime _payanam_ENDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpayanam_IDChanging(int value);
    partial void Onpayanam_IDChanged();
    partial void OnyearChanging(int value);
    partial void OnyearChanged();
    partial void Onpayanam_TITLEChanging(string value);
    partial void Onpayanam_TITLEChanged();
    partial void Onpayanam_STARTDATEChanging(System.DateTime value);
    partial void Onpayanam_STARTDATEChanged();
    partial void Onpayanam_ENDATEChanging(System.DateTime value);
    partial void Onpayanam_ENDATEChanged();
    #endregion
		
		public tab_VA_PAYANAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payanam_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int payanam_ID
		{
			get
			{
				return this._payanam_ID;
			}
			set
			{
				if ((this._payanam_ID != value))
				{
					this.Onpayanam_IDChanging(value);
					this.SendPropertyChanging();
					this._payanam_ID = value;
					this.SendPropertyChanged("payanam_ID");
					this.Onpayanam_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int NOT NULL")]
		public int year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payanam_TITLE", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string payanam_TITLE
		{
			get
			{
				return this._payanam_TITLE;
			}
			set
			{
				if ((this._payanam_TITLE != value))
				{
					this.Onpayanam_TITLEChanging(value);
					this.SendPropertyChanging();
					this._payanam_TITLE = value;
					this.SendPropertyChanged("payanam_TITLE");
					this.Onpayanam_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payanam_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime payanam_STARTDATE
		{
			get
			{
				return this._payanam_STARTDATE;
			}
			set
			{
				if ((this._payanam_STARTDATE != value))
				{
					this.Onpayanam_STARTDATEChanging(value);
					this.SendPropertyChanging();
					this._payanam_STARTDATE = value;
					this.SendPropertyChanged("payanam_STARTDATE");
					this.Onpayanam_STARTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payanam_ENDATE", DbType="DateTime NOT NULL")]
		public System.DateTime payanam_ENDATE
		{
			get
			{
				return this._payanam_ENDATE;
			}
			set
			{
				if ((this._payanam_ENDATE != value))
				{
					this.Onpayanam_ENDATEChanging(value);
					this.SendPropertyChanging();
					this._payanam_ENDATE = value;
					this.SendPropertyChanged("payanam_ENDATE");
					this.Onpayanam_ENDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_VA_SWAMY_REGISTRATION")]
	public partial class tab_VA_SWAMY_REGISTRATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _swamy_ID;
		
		private string _swamy_OLD_REG_NUMBER;
		
		private string _swamy_CODE;
		
		private string _swamy_NAME;
		
		private string _swamy_GENDER;
		
		private string _swamy_FATHER_SPOUSE_NAME;
		
		private System.Nullable<System.DateTime> _swamy_DOB;
		
		private string _swamy_PLACE;
		
		private string _swamy_ADDRESS;
		
		private string _swamy_MOBILE_NUMBER;
		
		private string _swamy_ALTERNATE_MOBILE;
		
		private string _swamy_DISTRICT;
		
		private string _swamy_BLOOD_GROUP;
		
		private int _swamy_MALAI_VISIT;
		
		private System.Nullable<System.DateTime> _swamy_KANNI_POOJAI_DATE;
		
		private bool _swamy_IS_MEMBER;
		
		private string _swamy_MEMBERSHIP_TYPE;
		
		private System.Nullable<System.DateTime> _swamy_MEMBERSHIP_EXPIRY_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onswamy_IDChanging(int value);
    partial void Onswamy_IDChanged();
    partial void Onswamy_OLD_REG_NUMBERChanging(string value);
    partial void Onswamy_OLD_REG_NUMBERChanged();
    partial void Onswamy_CODEChanging(string value);
    partial void Onswamy_CODEChanged();
    partial void Onswamy_NAMEChanging(string value);
    partial void Onswamy_NAMEChanged();
    partial void Onswamy_GENDERChanging(string value);
    partial void Onswamy_GENDERChanged();
    partial void Onswamy_FATHER_SPOUSE_NAMEChanging(string value);
    partial void Onswamy_FATHER_SPOUSE_NAMEChanged();
    partial void Onswamy_DOBChanging(System.Nullable<System.DateTime> value);
    partial void Onswamy_DOBChanged();
    partial void Onswamy_PLACEChanging(string value);
    partial void Onswamy_PLACEChanged();
    partial void Onswamy_ADDRESSChanging(string value);
    partial void Onswamy_ADDRESSChanged();
    partial void Onswamy_MOBILE_NUMBERChanging(string value);
    partial void Onswamy_MOBILE_NUMBERChanged();
    partial void Onswamy_ALTERNATE_MOBILEChanging(string value);
    partial void Onswamy_ALTERNATE_MOBILEChanged();
    partial void Onswamy_DISTRICTChanging(string value);
    partial void Onswamy_DISTRICTChanged();
    partial void Onswamy_BLOOD_GROUPChanging(string value);
    partial void Onswamy_BLOOD_GROUPChanged();
    partial void Onswamy_MALAI_VISITChanging(int value);
    partial void Onswamy_MALAI_VISITChanged();
    partial void Onswamy_KANNI_POOJAI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void Onswamy_KANNI_POOJAI_DATEChanged();
    partial void Onswamy_IS_MEMBERChanging(bool value);
    partial void Onswamy_IS_MEMBERChanged();
    partial void Onswamy_MEMBERSHIP_TYPEChanging(string value);
    partial void Onswamy_MEMBERSHIP_TYPEChanged();
    partial void Onswamy_MEMBERSHIP_EXPIRY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void Onswamy_MEMBERSHIP_EXPIRY_DATEChanged();
    #endregion
		
		public tab_VA_SWAMY_REGISTRATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int swamy_ID
		{
			get
			{
				return this._swamy_ID;
			}
			set
			{
				if ((this._swamy_ID != value))
				{
					this.Onswamy_IDChanging(value);
					this.SendPropertyChanging();
					this._swamy_ID = value;
					this.SendPropertyChanged("swamy_ID");
					this.Onswamy_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_OLD_REG_NUMBER", DbType="NVarChar(10)")]
		public string swamy_OLD_REG_NUMBER
		{
			get
			{
				return this._swamy_OLD_REG_NUMBER;
			}
			set
			{
				if ((this._swamy_OLD_REG_NUMBER != value))
				{
					this.Onswamy_OLD_REG_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._swamy_OLD_REG_NUMBER = value;
					this.SendPropertyChanged("swamy_OLD_REG_NUMBER");
					this.Onswamy_OLD_REG_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_CODE", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string swamy_CODE
		{
			get
			{
				return this._swamy_CODE;
			}
			set
			{
				if ((this._swamy_CODE != value))
				{
					this.Onswamy_CODEChanging(value);
					this.SendPropertyChanging();
					this._swamy_CODE = value;
					this.SendPropertyChanged("swamy_CODE");
					this.Onswamy_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string swamy_NAME
		{
			get
			{
				return this._swamy_NAME;
			}
			set
			{
				if ((this._swamy_NAME != value))
				{
					this.Onswamy_NAMEChanging(value);
					this.SendPropertyChanging();
					this._swamy_NAME = value;
					this.SendPropertyChanged("swamy_NAME");
					this.Onswamy_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_GENDER", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string swamy_GENDER
		{
			get
			{
				return this._swamy_GENDER;
			}
			set
			{
				if ((this._swamy_GENDER != value))
				{
					this.Onswamy_GENDERChanging(value);
					this.SendPropertyChanging();
					this._swamy_GENDER = value;
					this.SendPropertyChanged("swamy_GENDER");
					this.Onswamy_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_FATHER_SPOUSE_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string swamy_FATHER_SPOUSE_NAME
		{
			get
			{
				return this._swamy_FATHER_SPOUSE_NAME;
			}
			set
			{
				if ((this._swamy_FATHER_SPOUSE_NAME != value))
				{
					this.Onswamy_FATHER_SPOUSE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._swamy_FATHER_SPOUSE_NAME = value;
					this.SendPropertyChanged("swamy_FATHER_SPOUSE_NAME");
					this.Onswamy_FATHER_SPOUSE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> swamy_DOB
		{
			get
			{
				return this._swamy_DOB;
			}
			set
			{
				if ((this._swamy_DOB != value))
				{
					this.Onswamy_DOBChanging(value);
					this.SendPropertyChanging();
					this._swamy_DOB = value;
					this.SendPropertyChanged("swamy_DOB");
					this.Onswamy_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_PLACE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string swamy_PLACE
		{
			get
			{
				return this._swamy_PLACE;
			}
			set
			{
				if ((this._swamy_PLACE != value))
				{
					this.Onswamy_PLACEChanging(value);
					this.SendPropertyChanging();
					this._swamy_PLACE = value;
					this.SendPropertyChanged("swamy_PLACE");
					this.Onswamy_PLACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_ADDRESS", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string swamy_ADDRESS
		{
			get
			{
				return this._swamy_ADDRESS;
			}
			set
			{
				if ((this._swamy_ADDRESS != value))
				{
					this.Onswamy_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._swamy_ADDRESS = value;
					this.SendPropertyChanged("swamy_ADDRESS");
					this.Onswamy_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_MOBILE_NUMBER", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string swamy_MOBILE_NUMBER
		{
			get
			{
				return this._swamy_MOBILE_NUMBER;
			}
			set
			{
				if ((this._swamy_MOBILE_NUMBER != value))
				{
					this.Onswamy_MOBILE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._swamy_MOBILE_NUMBER = value;
					this.SendPropertyChanged("swamy_MOBILE_NUMBER");
					this.Onswamy_MOBILE_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_ALTERNATE_MOBILE", DbType="NVarChar(12)")]
		public string swamy_ALTERNATE_MOBILE
		{
			get
			{
				return this._swamy_ALTERNATE_MOBILE;
			}
			set
			{
				if ((this._swamy_ALTERNATE_MOBILE != value))
				{
					this.Onswamy_ALTERNATE_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._swamy_ALTERNATE_MOBILE = value;
					this.SendPropertyChanged("swamy_ALTERNATE_MOBILE");
					this.Onswamy_ALTERNATE_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_DISTRICT", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string swamy_DISTRICT
		{
			get
			{
				return this._swamy_DISTRICT;
			}
			set
			{
				if ((this._swamy_DISTRICT != value))
				{
					this.Onswamy_DISTRICTChanging(value);
					this.SendPropertyChanging();
					this._swamy_DISTRICT = value;
					this.SendPropertyChanged("swamy_DISTRICT");
					this.Onswamy_DISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_BLOOD_GROUP", DbType="NVarChar(15)")]
		public string swamy_BLOOD_GROUP
		{
			get
			{
				return this._swamy_BLOOD_GROUP;
			}
			set
			{
				if ((this._swamy_BLOOD_GROUP != value))
				{
					this.Onswamy_BLOOD_GROUPChanging(value);
					this.SendPropertyChanging();
					this._swamy_BLOOD_GROUP = value;
					this.SendPropertyChanged("swamy_BLOOD_GROUP");
					this.Onswamy_BLOOD_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_MALAI_VISIT", DbType="Int NOT NULL")]
		public int swamy_MALAI_VISIT
		{
			get
			{
				return this._swamy_MALAI_VISIT;
			}
			set
			{
				if ((this._swamy_MALAI_VISIT != value))
				{
					this.Onswamy_MALAI_VISITChanging(value);
					this.SendPropertyChanging();
					this._swamy_MALAI_VISIT = value;
					this.SendPropertyChanged("swamy_MALAI_VISIT");
					this.Onswamy_MALAI_VISITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_KANNI_POOJAI_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> swamy_KANNI_POOJAI_DATE
		{
			get
			{
				return this._swamy_KANNI_POOJAI_DATE;
			}
			set
			{
				if ((this._swamy_KANNI_POOJAI_DATE != value))
				{
					this.Onswamy_KANNI_POOJAI_DATEChanging(value);
					this.SendPropertyChanging();
					this._swamy_KANNI_POOJAI_DATE = value;
					this.SendPropertyChanged("swamy_KANNI_POOJAI_DATE");
					this.Onswamy_KANNI_POOJAI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_IS_MEMBER", DbType="Bit NOT NULL")]
		public bool swamy_IS_MEMBER
		{
			get
			{
				return this._swamy_IS_MEMBER;
			}
			set
			{
				if ((this._swamy_IS_MEMBER != value))
				{
					this.Onswamy_IS_MEMBERChanging(value);
					this.SendPropertyChanging();
					this._swamy_IS_MEMBER = value;
					this.SendPropertyChanged("swamy_IS_MEMBER");
					this.Onswamy_IS_MEMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_MEMBERSHIP_TYPE", DbType="NVarChar(50)")]
		public string swamy_MEMBERSHIP_TYPE
		{
			get
			{
				return this._swamy_MEMBERSHIP_TYPE;
			}
			set
			{
				if ((this._swamy_MEMBERSHIP_TYPE != value))
				{
					this.Onswamy_MEMBERSHIP_TYPEChanging(value);
					this.SendPropertyChanging();
					this._swamy_MEMBERSHIP_TYPE = value;
					this.SendPropertyChanged("swamy_MEMBERSHIP_TYPE");
					this.Onswamy_MEMBERSHIP_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swamy_MEMBERSHIP_EXPIRY_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> swamy_MEMBERSHIP_EXPIRY_DATE
		{
			get
			{
				return this._swamy_MEMBERSHIP_EXPIRY_DATE;
			}
			set
			{
				if ((this._swamy_MEMBERSHIP_EXPIRY_DATE != value))
				{
					this.Onswamy_MEMBERSHIP_EXPIRY_DATEChanging(value);
					this.SendPropertyChanging();
					this._swamy_MEMBERSHIP_EXPIRY_DATE = value;
					this.SendPropertyChanged("swamy_MEMBERSHIP_EXPIRY_DATE");
					this.Onswamy_MEMBERSHIP_EXPIRY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_VA_BUS_BOOKING")]
	public partial class tab_VA_BUS_BOOKING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _seat_ID;
		
		private int _payanam_ID;
		
		private int _user_ID;
		
		private int _bus_NUMBER;
		
		private int _seat_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onseat_IDChanging(int value);
    partial void Onseat_IDChanged();
    partial void Onpayanam_IDChanging(int value);
    partial void Onpayanam_IDChanged();
    partial void Onuser_IDChanging(int value);
    partial void Onuser_IDChanged();
    partial void Onbus_NUMBERChanging(int value);
    partial void Onbus_NUMBERChanged();
    partial void Onseat_NUMBERChanging(int value);
    partial void Onseat_NUMBERChanged();
    #endregion
		
		public tab_VA_BUS_BOOKING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int seat_ID
		{
			get
			{
				return this._seat_ID;
			}
			set
			{
				if ((this._seat_ID != value))
				{
					this.Onseat_IDChanging(value);
					this.SendPropertyChanging();
					this._seat_ID = value;
					this.SendPropertyChanged("seat_ID");
					this.Onseat_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payanam_ID", DbType="Int NOT NULL")]
		public int payanam_ID
		{
			get
			{
				return this._payanam_ID;
			}
			set
			{
				if ((this._payanam_ID != value))
				{
					this.Onpayanam_IDChanging(value);
					this.SendPropertyChanging();
					this._payanam_ID = value;
					this.SendPropertyChanged("payanam_ID");
					this.Onpayanam_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ID", DbType="Int NOT NULL")]
		public int user_ID
		{
			get
			{
				return this._user_ID;
			}
			set
			{
				if ((this._user_ID != value))
				{
					this.Onuser_IDChanging(value);
					this.SendPropertyChanging();
					this._user_ID = value;
					this.SendPropertyChanged("user_ID");
					this.Onuser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_NUMBER", DbType="Int NOT NULL")]
		public int bus_NUMBER
		{
			get
			{
				return this._bus_NUMBER;
			}
			set
			{
				if ((this._bus_NUMBER != value))
				{
					this.Onbus_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._bus_NUMBER = value;
					this.SendPropertyChanged("bus_NUMBER");
					this.Onbus_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_NUMBER", DbType="Int NOT NULL")]
		public int seat_NUMBER
		{
			get
			{
				return this._seat_NUMBER;
			}
			set
			{
				if ((this._seat_NUMBER != value))
				{
					this.Onseat_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._seat_NUMBER = value;
					this.SendPropertyChanged("seat_NUMBER");
					this.Onseat_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tab_VA_PAYANAM_BUS_DETAILS")]
	public partial class tab_VA_PAYANAM_BUS_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bus_ID;
		
		private int _bus_PAYANAM_NUMBER;
		
		private string _vehicle_TYPE;
		
		private int _bus_NUMBER;
		
		private int _bus_TOTAL_SEATS;
		
		private string _bus_REGISTRATION_NUMBER;
		
		private string _bus_DRIVER_NAME;
		
		private string _bus_DRIVER_MOBILE_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbus_IDChanging(int value);
    partial void Onbus_IDChanged();
    partial void Onbus_PAYANAM_NUMBERChanging(int value);
    partial void Onbus_PAYANAM_NUMBERChanged();
    partial void Onvehicle_TYPEChanging(string value);
    partial void Onvehicle_TYPEChanged();
    partial void Onbus_NUMBERChanging(int value);
    partial void Onbus_NUMBERChanged();
    partial void Onbus_TOTAL_SEATSChanging(int value);
    partial void Onbus_TOTAL_SEATSChanged();
    partial void Onbus_REGISTRATION_NUMBERChanging(string value);
    partial void Onbus_REGISTRATION_NUMBERChanged();
    partial void Onbus_DRIVER_NAMEChanging(string value);
    partial void Onbus_DRIVER_NAMEChanged();
    partial void Onbus_DRIVER_MOBILE_NUMBERChanging(string value);
    partial void Onbus_DRIVER_MOBILE_NUMBERChanged();
    #endregion
		
		public tab_VA_PAYANAM_BUS_DETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int bus_ID
		{
			get
			{
				return this._bus_ID;
			}
			set
			{
				if ((this._bus_ID != value))
				{
					this.Onbus_IDChanging(value);
					this.SendPropertyChanging();
					this._bus_ID = value;
					this.SendPropertyChanged("bus_ID");
					this.Onbus_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_PAYANAM_NUMBER", DbType="Int NOT NULL")]
		public int bus_PAYANAM_NUMBER
		{
			get
			{
				return this._bus_PAYANAM_NUMBER;
			}
			set
			{
				if ((this._bus_PAYANAM_NUMBER != value))
				{
					this.Onbus_PAYANAM_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._bus_PAYANAM_NUMBER = value;
					this.SendPropertyChanged("bus_PAYANAM_NUMBER");
					this.Onbus_PAYANAM_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_TYPE", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string vehicle_TYPE
		{
			get
			{
				return this._vehicle_TYPE;
			}
			set
			{
				if ((this._vehicle_TYPE != value))
				{
					this.Onvehicle_TYPEChanging(value);
					this.SendPropertyChanging();
					this._vehicle_TYPE = value;
					this.SendPropertyChanged("vehicle_TYPE");
					this.Onvehicle_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_NUMBER", DbType="Int NOT NULL")]
		public int bus_NUMBER
		{
			get
			{
				return this._bus_NUMBER;
			}
			set
			{
				if ((this._bus_NUMBER != value))
				{
					this.Onbus_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._bus_NUMBER = value;
					this.SendPropertyChanged("bus_NUMBER");
					this.Onbus_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_TOTAL_SEATS", DbType="Int NOT NULL")]
		public int bus_TOTAL_SEATS
		{
			get
			{
				return this._bus_TOTAL_SEATS;
			}
			set
			{
				if ((this._bus_TOTAL_SEATS != value))
				{
					this.Onbus_TOTAL_SEATSChanging(value);
					this.SendPropertyChanging();
					this._bus_TOTAL_SEATS = value;
					this.SendPropertyChanged("bus_TOTAL_SEATS");
					this.Onbus_TOTAL_SEATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_REGISTRATION_NUMBER", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string bus_REGISTRATION_NUMBER
		{
			get
			{
				return this._bus_REGISTRATION_NUMBER;
			}
			set
			{
				if ((this._bus_REGISTRATION_NUMBER != value))
				{
					this.Onbus_REGISTRATION_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._bus_REGISTRATION_NUMBER = value;
					this.SendPropertyChanged("bus_REGISTRATION_NUMBER");
					this.Onbus_REGISTRATION_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_DRIVER_NAME", DbType="NVarChar(50)")]
		public string bus_DRIVER_NAME
		{
			get
			{
				return this._bus_DRIVER_NAME;
			}
			set
			{
				if ((this._bus_DRIVER_NAME != value))
				{
					this.Onbus_DRIVER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._bus_DRIVER_NAME = value;
					this.SendPropertyChanged("bus_DRIVER_NAME");
					this.Onbus_DRIVER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bus_DRIVER_MOBILE_NUMBER", DbType="NVarChar(12)")]
		public string bus_DRIVER_MOBILE_NUMBER
		{
			get
			{
				return this._bus_DRIVER_MOBILE_NUMBER;
			}
			set
			{
				if ((this._bus_DRIVER_MOBILE_NUMBER != value))
				{
					this.Onbus_DRIVER_MOBILE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._bus_DRIVER_MOBILE_NUMBER = value;
					this.SendPropertyChanged("bus_DRIVER_MOBILE_NUMBER");
					this.Onbus_DRIVER_MOBILE_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
